import com.example.datencechatbotapp.Country

val AllCountries = mutableListOf<Country>(
    Country("Afghanistan","https://www.worldometers.info//img/flags/small/tn_af-flag.gif"),
    Country("Albania","https://www.worldometers.info//img/flags/small/tn_al-flag.gif"),
    Country("Algeria","https://www.worldometers.info//img/flags/small/tn_ag-flag.gif"),
    Country("Andorra","https://www.worldometers.info//img/flags/small/tn_an-flag.gif"),
    Country("Angola","https://www.worldometers.info//img/flags/small/tn_ao-flag.gif"),
    Country("Antigua and Barbuda","https://www.worldometers.info//img/flags/small/tn_ac-flag.gif"),
    Country("Argentina","https://www.worldometers.info//img/flags/small/tn_ar-flag.gif"),
    Country("Armenia","https://www.worldometers.info//img/flags/small/tn_am-flag.gif"),
    Country("Australia","https://www.worldometers.info//img/flags/small/tn_as-flag.gif"),
    Country("Austria","https://www.worldometers.info//img/flags/small/tn_au-flag.gif"),
    Country("Azerbaijan","https://www.worldometers.info//img/flags/small/tn_aj-flag.gif"),
    Country("Bahamas","https://www.worldometers.info//img/flags/small/tn_bf-flag.gif"),
    Country("Bahrain","https://www.worldometers.info//img/flags/small/tn_ba-flag.gif"),
    Country("Bangladesh","https://www.worldometers.info//img/flags/small/tn_bg-flag.gif"),
    Country("Barbados","https://www.worldometers.info//img/flags/small/tn_bb-flag.gif"),
    Country("Belarus","https://www.worldometers.info//img/flags/small/tn_bo-flag.gif"),
    Country("Belgium","https://www.worldometers.info//img/flags/small/tn_be-flag.gif"),
    Country("Belize","https://www.worldometers.info//img/flags/small/tn_bh-flag.gif"),
    Country("Benin","https://www.worldometers.info//img/flags/small/tn_bn-flag.gif"),
    Country("Bhutan","https://www.worldometers.info//img/flags/small/tn_bt-flag.gif"),
    Country("Bolivia","https://www.worldometers.info//img/flags/small/tn_bl-flag.gif"),
    Country("Bosnia and Herzegovina","https://www.worldometers.info//img/flags/small/tn_bk-flag.gif"),
    Country("Botswana","https://www.worldometers.info//img/flags/small/tn_bc-flag.gif"),
    Country("Brazil","https://www.worldometers.info//img/flags/small/tn_br-flag.gif"),
    Country("Brunei","https://www.worldometers.info//img/flags/small/tn_bx-flag.gif"),
    Country("Bulgaria","https://www.worldometers.info//img/flags/small/tn_bu-flag.gif"),
    Country("Burkina Faso","https://www.worldometers.info//img/flags/small/tn_uv-flag.gif"),
    Country("Burundi","https://www.worldometers.info//img/flags/small/tn_by-flag.gif"),
    Country("Côte d'Ivoire","https://www.worldometers.info//img/flags/small/tn_iv-flag.gif"),
    Country("Cabo Verde","https://www.worldometers.info//img/flags/small/tn_cv-flag.gif"),
    Country("Cambodia","https://www.worldometers.info//img/flags/small/tn_cb-flag.gif"),
    Country("Cameroon","https://www.worldometers.info//img/flags/small/tn_cm-flag.gif"),
    Country("Canada","https://www.worldometers.info//img/flags/small/tn_ca-flag.gif"),
    Country("CAR","https://www.worldometers.info//img/flags/small/tn_ct-flag.gif"),
    Country("Chad","https://www.worldometers.info//img/flags/small/tn_cd-flag.gif"),
    Country("Chile","https://www.worldometers.info//img/flags/small/tn_ci-flag.gif"),
    Country("China","https://www.worldometers.info//img/flags/small/tn_ch-flag.gif"),
    Country("Colombia","https://www.worldometers.info//img/flags/small/tn_co-flag.gif"),
    Country("Comoros","https://www.worldometers.info//img/flags/small/tn_cn-flag.gif"),
    Country("Congo","https://www.worldometers.info//img/flags/small/tn_cg-flag.gif"),
    Country("Costa Rica","https://www.worldometers.info//img/flags/small/tn_cs-flag.gif"),
    Country("Croatia","https://www.worldometers.info//img/flags/small/tn_hr-flag.gif"),
    Country("Cuba","https://www.worldometers.info//img/flags/small/tn_cu-flag.gif"),
    Country("Cyprus","https://www.worldometers.info//img/flags/small/tn_cy-flag.gif"),
    Country("Czechia","https://www.worldometers.info//img/flags/small/tn_ez-flag.gif"),
    Country("Denmark","https://www.worldometers.info//img/flags/small/tn_da-flag.gif"),
    Country("Djibouti","https://www.worldometers.info//img/flags/small/tn_dj-flag.gif"),
    Country("Dominica","https://www.worldometers.info//img/flags/small/tn_do-flag.gif"),
    Country("Dominican Republic","https://www.worldometers.info//img/flags/small/tn_dr-flag.gif"),
    Country("DPRK","https://www.worldometers.info//img/flags/small/tn_kn-flag.gif"),
    Country("DRC","https://www.worldometers.info//img/flags/small/tn_congo-flag.gif"),
    Country("Ecuador","https://www.worldometers.info//img/flags/small/tn_ec-flag.gif"),
    Country("Egypt","https://www.worldometers.info//img/flags/small/tn_eg-flag.gif"),
    Country("El Salvador","https://www.worldometers.info//img/flags/small/tn_es-flag.gif"),
    Country("Equatorial Guinea","https://www.worldometers.info//img/flags/small/tn_ek-flag.gif"),
    Country("Eritrea","https://www.worldometers.info//img/flags/small/tn_er-flag.gif"),
    Country("Estonia","https://www.worldometers.info//img/flags/small/tn_en-flag.gif"),
    Country("Eswatini","https://www.worldometers.info//img/flags/small/tn_wz-flag.gif"),
    Country("Ethiopia","https://www.worldometers.info//img/flags/small/tn_et-flag.gif"),
    Country("Fiji","https://www.worldometers.info//img/flags/small/tn_fj-flag.gif"),
    Country("Finland","https://www.worldometers.info//img/flags/small/tn_fi-flag.gif"),
    Country("France","https://www.worldometers.info//img/flags/small/tn_fr-flag.gif"),
    Country("Gabon","https://www.worldometers.info//img/flags/small/tn_gb-flag.gif"),
    Country("Gambia","https://www.worldometers.info//img/flags/small/tn_ga-flag.gif"),
    Country("Georgia","https://www.worldometers.info//img/flags/small/tn_gg-flag.gif"),
    Country("Germany","https://www.worldometers.info//img/flags/small/tn_gm-flag.gif"),
    Country("Ghana","https://www.worldometers.info//img/flags/small/tn_gh-flag.gif"),
    Country("Greece","https://www.worldometers.info//img/flags/small/tn_gr-flag.gif"),
    Country("Grenada","https://www.worldometers.info//img/flags/small/tn_gj-flag.gif"),
    Country("Guatemala","https://www.worldometers.info//img/flags/small/tn_gt-flag.gif"),
    Country("Guinea","https://www.worldometers.info//img/flags/small/tn_gv-flag.gif"),
    Country("Guinea-Bissau","https://www.worldometers.info//img/flags/small/tn_pu-flag.gif"),
    Country("Guyana","https://www.worldometers.info//img/flags/small/tn_gy-flag.gif"),
    Country("Haiti","https://www.worldometers.info//img/flags/small/tn_ha-flag.gif"),
    Country("Holy See","https://www.worldometers.info//img/flags/small/tn_vt-flag.gif"),
    Country("Honduras","https://www.worldometers.info//img/flags/small/tn_ho-flag.gif"),
    Country("Hungary","https://www.worldometers.info//img/flags/small/tn_hu-flag.gif"),
    Country("Iceland","https://www.worldometers.info//img/flags/small/tn_ic-flag.gif"),
    Country("India","https://www.worldometers.info//img/flags/small/tn_in-flag.gif"),
    Country("Indonesia","https://www.worldometers.info//img/flags/small/tn_id-flag.gif"),
    Country("Iran","https://www.worldometers.info//img/flags/small/tn_ir-flag.gif"),
    Country("Iraq","https://www.worldometers.info//img/flags/small/tn_iz-flag.gif"),
    Country("Ireland","https://www.worldometers.info//img/flags/small/tn_ei-flag.gif"),
    Country("Israel","https://www.worldometers.info//img/flags/small/tn_is-flag.gif"),
    Country("Italy","https://www.worldometers.info//img/flags/small/tn_it-flag.gif"),
    Country("Jamaica","https://www.worldometers.info//img/flags/small/tn_jm-flag.gif"),
    Country("Japan","https://www.worldometers.info//img/flags/small/tn_ja-flag.gif"),
    Country("Jordan","https://www.worldometers.info//img/flags/small/tn_jo-flag.gif"),
    Country("Kazakhstan","https://www.worldometers.info//img/flags/small/tn_kz-flag.gif"),
    Country("Kenya","https://www.worldometers.info//img/flags/small/tn_ke-flag.gif"),
    Country("Kiribati","https://www.worldometers.info//img/flags/small/tn_kr-flag.gif"),
    Country("Kuwait","https://www.worldometers.info//img/flags/small/tn_ku-flag.gif"),
    Country("Kyrgyzstan","https://www.worldometers.info//img/flags/small/tn_kg-flag.gif"),
    Country("Laos","https://www.worldometers.info//img/flags/small/tn_la-flag.gif"),
    Country("Latvia","https://www.worldometers.info//img/flags/small/tn_lg-flag.gif"),
    Country("Lebanon","https://www.worldometers.info//img/flags/small/tn_le-flag.gif"),
    Country("Lesotho","https://www.worldometers.info//img/flags/small/tn_lt-flag.gif"),
    Country("Liberia","https://www.worldometers.info//img/flags/small/tn_li-flag.gif"),
    Country("Libya","https://www.worldometers.info//img/flags/small/tn_ly-flag.gif"),
    Country("Liechtenstein","https://www.worldometers.info//img/flags/small/tn_ls-flag.gif"),
    Country("Lithuania","https://www.worldometers.info//img/flags/small/tn_lh-flag.gif"),
    Country("Luxembourg","https://www.worldometers.info//img/flags/small/tn_lu-flag.gif"),
    Country("Madagascar","https://www.worldometers.info//img/flags/small/tn_ma-flag.gif"),
    Country("Malawi","https://www.worldometers.info//img/flags/small/tn_mi-flag.gif"),
    Country("Malaysia","https://www.worldometers.info//img/flags/small/tn_my-flag.gif"),
    Country("Maldives","https://www.worldometers.info//img/flags/small/tn_mv-flag.gif"),
    Country("Mali","https://www.worldometers.info//img/flags/small/tn_ml-flag.gif"),
    Country("Malta","https://www.worldometers.info//img/flags/small/tn_mt-flag.gif"),
    Country("Marshall Islands","https://www.worldometers.info//img/flags/small/tn_rm-flag.gif"),
    Country("Mauritania","https://www.worldometers.info//img/flags/small/tn_mr-flag.gif"),
    Country("Mauritius","https://www.worldometers.info//img/flags/small/tn_mp-flag.gif"),
    Country("Mexico","https://www.worldometers.info//img/flags/small/tn_mx-flag.gif"),
    Country("Micronesia","https://www.worldometers.info//img/flags/small/tn_fm-flag.gif"),
    Country("Moldova","https://www.worldometers.info//img/flags/small/tn_md-flag.gif"),
    Country("Monaco","https://www.worldometers.info//img/flags/small/tn_mn-flag.gif"),
    Country("Mongolia","https://www.worldometers.info//img/flags/small/tn_mg-flag.gif"),
    Country("Montenegro","https://www.worldometers.info//img/flags/small/tn_mj-flag.gif"),
    Country("Morocco","https://www.worldometers.info//img/flags/small/tn_mo-flag.gif"),
    Country("Mozambique","https://www.worldometers.info//img/flags/small/tn_mz-flag.gif"),
    Country("Myanmar","https://www.worldometers.info//img/flags/small/tn_bm-flag.gif"),
    Country("Namibia","https://www.worldometers.info//img/flags/small/tn_wa-flag.gif"),
    Country("Nauru","https://www.worldometers.info//img/flags/small/tn_nr-flag.gif"),
    Country("Nepal","https://www.worldometers.info//img/flags/small/tn_np-flag.gif"),
    Country("Netherlands","https://www.worldometers.info//img/flags/small/tn_nl-flag.gif"),
    Country("New Zealand","https://www.worldometers.info//img/flags/small/tn_nz-flag.gif"),
    Country("Nicaragua","https://www.worldometers.info//img/flags/small/tn_nu-flag.gif"),
    Country("Niger","https://www.worldometers.info//img/flags/small/tn_ng-flag.gif"),
    Country("Nigeria","https://www.worldometers.info//img/flags/small/tn_ni-flag.gif"),
    Country("North Macedonia","https://www.worldometers.info//img/flags/small/tn_mk-flag.gif"),
    Country("Norway","https://www.worldometers.info//img/flags/small/tn_no-flag.gif"),
    Country("Oman","https://www.worldometers.info//img/flags/small/tn_mu-flag.gif"),
    Country("Pakistan","https://www.worldometers.info//img/flags/small/tn_pk-flag.gif"),
    Country("Palau","https://www.worldometers.info//img/flags/small/tn_ps-flag.gif"),
    Country("Panama","https://www.worldometers.info//img/flags/small/tn_pm-flag.gif"),
    Country("Papua New Guinea","https://www.worldometers.info//img/flags/small/tn_pp-flag.gif"),
    Country("Paraguay","https://www.worldometers.info//img/flags/small/tn_pa-flag.gif"),
    Country("Peru","https://www.worldometers.info//img/flags/small/tn_pe-flag.gif"),
    Country("Philippines","https://www.worldometers.info//img/flags/small/tn_rp-flag.gif"),
    Country("Poland","https://www.worldometers.info//img/flags/small/tn_pl-flag.gif"),
    Country("Portugal","https://www.worldometers.info//img/flags/small/tn_po-flag.gif"),
    Country("Qatar","https://www.worldometers.info//img/flags/small/tn_qa-flag.gif"),
    Country("Romania","https://www.worldometers.info//img/flags/small/tn_ro-flag.gif"),
    Country("Russia","https://www.worldometers.info//img/flags/small/tn_rs-flag.gif"),
    Country("Rwanda","https://www.worldometers.info//img/flags/small/tn_rw-flag.gif"),
    Country("Saint Kitts and Nevis","https://www.worldometers.info//img/flags/small/tn_sc-flag.gif"),
    Country("Saint Lucia","https://www.worldometers.info//img/flags/small/tn_st-flag.gif"),
    Country("Samoa","https://www.worldometers.info//img/flags/small/tn_ws-flag.gif"),
    Country("San Marino","https://www.worldometers.info//img/flags/small/tn_sm-flag.gif"),
    Country("Sao Tome and Principe","https://www.worldometers.info//img/flags/small/tn_tp-flag.gif"),
    Country("Saudi Arabia","https://www.worldometers.info//img/flags/small/tn_sa-flag.gif"),
    Country("Senegal","https://www.worldometers.info//img/flags/small/tn_sg-flag.gif"),
    Country("Serbia","https://www.worldometers.info//img/flags/small/tn_ri-flag.gif"),
    Country("Seychelles","https://www.worldometers.info//img/flags/small/tn_se-flag.gif"),
    Country("Sierra Leone","https://www.worldometers.info//img/flags/small/tn_sl-flag.gif"),
    Country("Singapore","https://www.worldometers.info//img/flags/small/tn_sn-flag.gif"),
    Country("Slovakia","https://www.worldometers.info//img/flags/small/tn_lo-flag.gif"),
    Country("Slovenia","https://www.worldometers.info//img/flags/small/tn_si-flag.gif"),
    Country("Solomon Islands","https://www.worldometers.info//img/flags/small/tn_bp-flag.gif"),
    Country("Somalia","https://www.worldometers.info//img/flags/small/tn_so-flag.gif"),
    Country("South Africa","https://www.worldometers.info//img/flags/small/tn_sf-flag.gif"),
    Country("South Korea","https://www.worldometers.info//img/flags/small/tn_ks-flag.gif"),
    Country("South Sudan","https://www.worldometers.info//img/flags/small/tn_od-flag.gif"),
    Country("Spain","https://www.worldometers.info//img/flags/small/tn_sp-flag.gif"),
    Country("Sri Lanka","https://www.worldometers.info//img/flags/small/tn_ce-flag.gif"),
    Country("St. Vincent Grenadines","https://www.worldometers.info//img/flags/small/tn_vc-flag.gif"),
    Country("State of Palestine","https://www.worldometers.info//img/flags/small/tn_palestine-flag.gif"),
    Country("Sudan","https://www.worldometers.info//img/flags/small/tn_su-flag.gif"),
    Country("Suriname","https://www.worldometers.info//img/flags/small/tn_ns-flag.gif"),
    Country("Sweden","https://www.worldometers.info//img/flags/small/tn_sw-flag.gif"),
    Country("Switzerland","https://www.worldometers.info//img/flags/small/tn_sz-flag.gif"),
    Country("Syria","https://www.worldometers.info//img/flags/small/tn_sy-flag.gif"),
    Country("Tajikistan","https://www.worldometers.info//img/flags/small/tn_ti-flag.gif"),
    Country("Tanzania","https://www.worldometers.info//img/flags/small/tn_tz-flag.gif"),
    Country("Thailand","https://www.worldometers.info//img/flags/small/tn_th-flag.gif"),
    Country("Timor-Leste","https://www.worldometers.info//img/flags/small/tn_tt-flag.gif"),
    Country("Togo","https://www.worldometers.info//img/flags/small/tn_to-flag.gif"),
    Country("Tonga","https://www.worldometers.info//img/flags/small/tn_tn-flag.gif"),
    Country("Trinidad and Tobago","https://www.worldometers.info//img/flags/small/tn_td-flag.gif"),
    Country("Tunisia","https://www.worldometers.info//img/flags/small/tn_ts-flag.gif"),
    Country("Turkey","https://www.worldometers.info//img/flags/small/tn_tu-flag.gif"),
    Country("Turkmenistan","https://www.worldometers.info//img/flags/small/tn_tx-flag.gif"),
    Country("Tuvalu","https://www.worldometers.info//img/flags/small/tn_tv-flag.gif"),
    Country("U.A.E.","https://www.worldometers.info//img/flags/small/tn_ae-flag.gif"),
    Country("U.K.","https://www.worldometers.info//img/flags/small/tn_uk-flag.gif"),
    Country("U.S.","https://www.worldometers.info//img/flags/small/tn_us-flag.gif"),
    Country("Uganda","https://www.worldometers.info//img/flags/small/tn_ug-flag.gif"),
    Country("Ukraine","https://www.worldometers.info//img/flags/small/tn_up-flag.gif"),
    Country("Uruguay","https://www.worldometers.info//img/flags/small/tn_uy-flag.gif"),
    Country("Uzbekistan","https://www.worldometers.info//img/flags/small/tn_uz-flag.gif"),
    Country("Vanuatu","https://www.worldometers.info//img/flags/small/tn_nh-flag.gif"),
    Country("Venezuela","https://www.worldometers.info//img/flags/small/tn_ve-flag.gif"),
    Country("Vietnam","https://www.worldometers.info//img/flags/small/tn_vm-flag.gif"),
    Country("Yemen","https://www.worldometers.info//img/flags/small/tn_ym-flag.gif"),
    Country("Zambia","https://www.worldometers.info//img/flags/small/tn_za-flag.gif"),
    Country("Zimbabwe","https://www.worldometers.info//img/flags/small/tn_zi-flag.gif"),

    )